# Generated by Django 4.1.6 on 2023-03-07 16:08

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0003_sitesetting_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link', models.CharField(max_length=150, verbose_name='لینک فضای مجازی')),
                ('social_image', models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_image_path, verbose_name='تصویر فضای مجازی')),
            ],
        ),
    ]
