# Generated by Django 4.1.6 on 2023-03-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0004_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'تنظیمات فضای مجازی', 'verbose_name_plural': 'مدیریت فضای مجازی'},
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='social_name',
            field=models.CharField(max_length=150, null=True, verbose_name='اسم شبکه فضای مجازی'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_link',
            field=models.CharField(max_length=150, null=True, verbose_name='لینک فضای مجازی'),
        ),
    ]
